"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const admin_1 = require("../middleware/admin");
const admin_controller_1 = require("../controllers/admin.controller");
exports.adminRouter = (0, express_1.Router)();
exports.adminRouter.use(auth_1.requireAuth, admin_1.requireAdmin);
exports.adminRouter.get("/standards", admin_controller_1.listStandards);
exports.adminRouter.post("/standards", admin_controller_1.createStandard);
exports.adminRouter.patch("/standards/:id", admin_controller_1.updateStandard);
exports.adminRouter.delete("/standards/:id", admin_controller_1.deleteStandard);
exports.adminRouter.get("/subjects", admin_controller_1.listSubjects);
exports.adminRouter.post("/subjects", admin_controller_1.createSubject);
exports.adminRouter.patch("/subjects/:id", admin_controller_1.updateSubject);
exports.adminRouter.delete("/subjects/:id", admin_controller_1.deleteSubject);
exports.adminRouter.get("/units", admin_controller_1.listUnits);
exports.adminRouter.post("/units", admin_controller_1.createUnit);
exports.adminRouter.patch("/units/:id", admin_controller_1.updateUnit);
exports.adminRouter.delete("/units/:id", admin_controller_1.deleteUnit);
exports.adminRouter.get("/chapters", admin_controller_1.listChapters);
exports.adminRouter.post("/chapters", admin_controller_1.createChapter);
exports.adminRouter.patch("/chapters/:id", admin_controller_1.updateChapter);
exports.adminRouter.delete("/chapters/:id", admin_controller_1.deleteChapter);
exports.adminRouter.get("/lessons", admin_controller_1.listLessons);
exports.adminRouter.post("/lessons", admin_controller_1.createLesson);
exports.adminRouter.patch("/lessons/:id", admin_controller_1.updateLesson);
exports.adminRouter.delete("/lessons/:id", admin_controller_1.deleteLesson);
exports.adminRouter.get("/quizzes/latest", admin_controller_1.getLatestQuizForLesson);
exports.adminRouter.post("/quizzes/version", admin_controller_1.createQuizVersion);
exports.adminRouter.patch("/quizzes/:id/published", admin_controller_1.setQuizPublished);
exports.adminRouter.patch("/quizzes/:id/publish", admin_controller_1.publishQuizExclusive);
exports.adminRouter.patch("/standards/:id/restore", admin_controller_1.restoreStandard);
exports.adminRouter.patch("/subjects/:id/restore", admin_controller_1.restoreSubject);
exports.adminRouter.patch("/units/:id/restore", admin_controller_1.restoreUnit);
exports.adminRouter.patch("/chapters/:id/restore", admin_controller_1.restoreChapter);
exports.adminRouter.patch("/lessons/:id/restore", admin_controller_1.restoreLesson);
exports.adminRouter.patch("/quizzes/:id/restore", admin_controller_1.restoreQuiz);
exports.adminRouter.get("/jobs/status", admin_controller_1.jobsStatus);
exports.adminRouter.get("/audit", admin_controller_1.listAdminAuditLogs);