"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRouter = void 0;
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
exports.authRouter = (0, express_1.Router)();
exports.authRouter.post("/auth/request-otp", auth_controller_1.requestOtp);
exports.authRouter.post("/auth/verify-otp", auth_controller_1.verifyOtp);
exports.authRouter.post("/auth/refresh", auth_controller_1.refresh);
exports.authRouter.post("/auth/logout", auth_controller_1.logout);
exports.authRouter.post("/auth/google", auth_controller_1.googleSignIn);