"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.curriculumRouter = void 0;
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const curriculum_controller_1 = require("../controllers/curriculum.controller");
exports.curriculumRouter = (0, express_1.Router)();
exports.curriculumRouter.get("/curriculum/standards", curriculum_controller_1.getStandards);
exports.curriculumRouter.get("/curriculum/subjects", curriculum_controller_1.getSubjects);
exports.curriculumRouter.get("/units", curriculum_controller_1.getUnits);
exports.curriculumRouter.get("/chapters", curriculum_controller_1.getChapters);
exports.curriculumRouter.get("/lessons", auth_1.requireAuth, auth_1.profileGate, curriculum_controller_1.getLessons);