"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const user_controller_1 = require("../controllers/user.controller");
exports.userRouter = (0, express_1.Router)();
exports.userRouter.get("/me", auth_1.requireAuth, user_controller_1.getMe);
exports.userRouter.patch("/me/profile", auth_1.requireAuth, user_controller_1.completeProfile);
exports.userRouter.patch("/me/onboarding", auth_1.requireAuth, user_controller_1.completeOnboarding);